### ISSUE TITLE
Auth endpoint parameter 'Code' unclear in Docs

### ISSUE THREAD

**Issue by aeriondyseti** [MindsEyeSociety/mes-hub#12]
In the documentation for the Authentication endpoint, it is unclear exactly what the {code} parameter is supposed to be. Am I correct in assuming that it should be the token for the user submitting the request, or are we using Bearer Auth or some other mechanism to provide that information?

**Comment by ChaosExAnima** [comment]
That information is per client app, and stored in the clients.json file. I'll update the documentation.

**Comment by aeriondyseti** [comment]
Not having dug into the implementation details of this yet, could you give me an example of a successful app call should look like?

**Comment by ChaosExAnima** [comment]
Sure. If you don't have a token (or an invalid one), redirect the user to this URL:
```
GET http://localhost:3000/v1/auth/signin/{code}
```
Where `{code}` is a string in the `config/client.json` that maps to your app URL. The auth system will redirect the user through the OAuth flow, and direct them back to the code URL with both a cookie and query string of `token` set to the valid token.

@AerionDyseti - Any questions?
